### ISSUE TITLE
Typo in "download mods" screenshot

### ISSUE THREAD

**Issue by Ekain06** [PolyMC/polymc.github.io#108]
In the polymc.org homepage, scroll down until you reach the "Download Mods" header and look at the screenshot. In the bottom part it says "sort by relevence" instead of "sort by relevance". 

I don't know if this typo is also present in the actual launcher since I'm away from my computer right now.

**Comment by DioEgizio** [comment]
I think this was fixed in the launcher a while ago. 
Those screenshot were taken with an ancient version of PolyMC

**Comment by flowln** [comment]
The images got updated, and the typo is now fixed :)
