### ISSUE TITLE
[Suggestion] Harmonize look and feel of PolyMC screenshots

### ISSUE THREAD

**Issue by dschemp** [PolyMC/polymc.github.io#118]
Hey,

currently multiple looks of the PolyMC launcher are presented on the website ranging from plain KDE/Plasma, to customized Plasma and macOS.
It would be great if the style of the PolyMC launcher would be consistent across the website, both in terms of looks as well as size.
Maybe there is some sort of way to automatically create screenshots in a consistent environment?

Examples:
https://polymc.org/
https://polymc.org/wiki/help-pages/APIs/ (uses a language other than English)
https://polymc.org/wiki/help-pages/Java-settings/ / https://polymc.org/wiki/help-pages/Loader-mods/

**Comment by DioEgizio** [comment]
> https://polymc.org/wiki/help-pages/APIs/ (uses a language other than English)

this is my fault, going to fix soon with a pr

**Comment by DioEgizio** [comment]
#119
