### ISSUE TITLE
Different colors for the social media buttons

### ISSUE THREAD

**Issue by flowln** [PolyMC/polymc.github.io#144]
Currently the button on the top-right of the top bar are greened when you hover over them. It would be cool if, instead, each button had their own color when hovered, like blue for Discord, orange for Reddit, etc... :)

**Comment by ZekeSmith** [comment]
Hmm ill look into it, not that hard to implement.

**Comment by ZekeSmith** [comment]
I have tested and I think I prefer sticking the the defined branding colors. Its honestly a preference thing and doesnt matter at the end of the day imo.
