### ISSUE TITLE
Suggestion to add a news piece covering the recently introduced player reporting system to the site

### ISSUE THREAD

**Issue by TheMCNerd2017** [PolyMC/polymc.github.io#167]
Mojang added player reporting to Java edition today in the latest 1.19.1 snapshot. So far it only allows for reporting chat violations, but it may be extended in the future to allow reporting other actions as well. I suggest that a news post covering this be added to the site as the change itself is quite controversial and could lead to game-wide punishments like on Bedrock edition.

Also sorry if this isn't the right way to suggest a potential news piece for the website, I did not know the correct way to suggest a potential news piece.

**Comment by ZekeSmith** [comment]
I dont disagree, ill discuss this with the other maintainers.

**Comment by ZekeSmith** [comment]
Discussion has concluded this is out of scope, however I may have a write up on the wiki regarding circumventing the report system with mods.
