### ISSUE TITLE
Prepare for 1.4.0

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/polymc.github.io#179]
1.4.0 will be a huge release. The website will need changes too.

- [x] Updating the build instructions to mention qt6 and always say to use mingw32 on windows.
- [x] Updating the screenshots to promote the new 1.4.0 features, including mod updating and news reading for example. 
   - [x] this also includes updating linux screenshots in general because the current ones don't have any theme (they use fusion) and so don't look perfectly 
   - [ ] this also includes updating [org.polymc.PolyMC.metainfo.xml.in](https://github.com/PolyMC/PolyMC/blob/develop/program_info/org.polymc.PolyMC.metainfo.xml.in) to not break flatpak
- [x] Add Qt5 packages and explain the difference with normal qt6 ones

probably more :P

**Comment by ZekeSmith** [comment]
I will have to assign someone else to:
> Updating the build instructions to mention qt6 and always say to use mingw32 on windows.

I can work on the other requirements.

**Comment by DioEgizio** [comment]
Screenshots still not updated D:

**Comment by DioEgizio** [comment]
ok now they are, but someone needs to do a pr to edit https://github.com/PolyMC/PolyMC/blob/develop/program_info/org.polymc.PolyMC.metainfo.xml.in to not break flatpak

**Comment by DioEgizio** [comment]
Since I opened a pr to do that, I think this can be closed
