### ISSUE TITLE
plain HTML version

### ISSUE THREAD

**Issue by binex-dsk** [PolyMC/polymc.github.io#18]
for lynx and similar browsers or for when you don't want your computer's CPU and RAM usage to spike to 60% when loading the page

**Comment by glowiak** [comment]
use gopher

**Comment by ZekeSmith** [comment]
The website is plain html compatible. There is no need for this pull request.

**Comment by binex-dsk** [comment]
> The website is plain html compatible. There is no need for this pull request.

No it's not. This doesn't load properly on Lynx.

**Comment by binex-dsk** [comment]
Damn must've been a skill issue. Seems to work now false alarm.

I'd still honestly like to see this, as I much, much prefer the style of plain old HTML with no CSS or anything else, with minimal imagery.

If nobody cares enough I'll PR it.

**Comment by ZekeSmith** [comment]
Just use the page in plain html nothing is stopping you
