### ISSUE TITLE
Site does not appear on google!

### ISSUE THREAD

**Issue by WesleyBryie** [PolyMC/polymc.github.io#189]
![image](https://user-images.githubusercontent.com/93141203/180260564-edcb30e7-1847-43b0-a782-98e102a6b6c1.png)

**Comment by txtsd** [comment]
Top result on DDG. Wonder why Google hates us.

![Screenshot 2022-07-21 at 21-42-58 polymc at DuckDuckGo](https://user-images.githubusercontent.com/768728/180262743-83ee4f19-3b3d-416d-a8cb-05baa4997e90.png)

**Comment by WesleyBryie** [comment]
maybe you'll want to contact google.

**Comment by ZekeSmith** [comment]
Very weird it was top result not to long ago. Ill check page seo mabye a broken robots.txt or sitemap.

**Comment by ZekeSmith** [comment]
Searching PolyMC Website returns first result. Thats even weirder.

**Comment by DioEgizio** [comment]
huh, still first result on google for me

**Comment by txtsd** [comment]
@DioEgizio try in incognito, without logging in etc.

**Comment by DioEgizio** [comment]
Still first result

**Comment by ZekeSmith** [comment]
This is no longer an issue I cant replicate it anymore.
