### ISSUE TITLE
The PolyMC start page doesn't make clear what PolyMC actually is

### ISSUE THREAD

**Issue by TGRush** [PolyMC/polymc.github.io#22]
### Redistributability and Freedom, because MultiMC didn't wanna do it themselves

maybe that could be put at the bottom of the "Main Features" section or something?

**Comment by DioEgizio** [comment]
> Redistributability and Freedom, because MultiMC didn't wanna do it themselves

I don't think we should be so hostile in the main page

**Comment by DioEgizio** [comment]
Also PolyMC isn't just Redistributability and Freedom anymore

**Comment by TGRush** [comment]
> I don't think we should be so hostile in the main page 

that wasn't supposed to be a suggestion on what exactly the page should say
though your comment id fair lol

**Comment by TGRush** [comment]
> Also PolyMC isn't just Redistributability and Freedom anymore

huh did I miss something

**Comment by DioEgizio** [comment]
You missed what polymc 1.1.0 will be I guess
Take a look at the commit history, polymc has a lot of new features that multimc doesn't have

**Comment by ZekeSmith** [comment]
Yeah I think the landing page is fine and outlines our features its maybe a little cookie cutter but I am going to update it with the 1.1.0 release anyways I am going to close this issue for now as it doesn't really outline the issue well and I think the current landing page is fine.
