### ISSUE TITLE
Wrong icon in web search

### ISSUE THREAD

**Issue by flowln** [PolyMC/polymc.github.io#32]
When using DuckDuckGo while searching for "polymc", this page shows up, but not with the current PolyMC icon:
![image](https://user-images.githubusercontent.com/9145768/157294400-4e0461b3-db55-4a72-b941-36cb13bbcccd.png)

**Comment by DioEgizio** [comment]
Ddg moment I guess, https://polymc.org/favicon.ico

> When using DuckDuckGo while searching for "polymc", this page shows up, but not with the current PolyMC icon: ![image](https://user-images.githubusercontent.com/9145768/157294400-4e0461b3-db55-4a72-b941-36cb13bbcccd.png)

**Comment by flowln** [comment]
Maybe a cache problem on their end then? rip favicon T_T

**Comment by flowln** [comment]
Ok, I guess it will update soon, so I'll close this
![image](https://user-images.githubusercontent.com/9145768/157300002-700db0b3-c80a-482a-814c-526ac425f61d.png)
