### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by Lutitious** [PolyMC/polymc.github.io#90]
I think it would be nice to add a roadmap to the website to track future goals of the project.

**Comment by ZekeSmith** [comment]
hmm what do you think would be the best way to implement this? mabye like it pulls from the github milestones or something

**Comment by Rahul-Imran** [comment]
That sounds like a good idea

**Comment by ZekeSmith** [comment]
Roadmap is out of scope for a large opensource project its unpredicatble and I dont want users to contstantly ask for features based on a roadmap unless we can ensure them.
